#!/usr/bin/env bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
    then
        cd $OPENSHIFT_DATA_DIR
		mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_20 ]
    then
        cd $OPENSHIFT_DATA_DIR
        wget http://www.java.net/download/jdk8u20/archive/b17/binaries/jdk-8u20-ea-bin-b17-linux-x64-04_jun_2014.tar.gz
        tar xvf *.tar.gz
        rm -f *.tar.gz
        mv ./jdk1.8.0_20 ./java
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.3 ]
    then
        cd $OPENSHIFT_DATA_DIR
        wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
        tar xvf *.tar.gz
        rm -f *.tar.gz
        mv ./apache-maven-3.3.3 ./maven
fi

if [ ! -d $OPENSHIFT_DATA_DIR/maven/repository ]
    then
        cd $OPENSHIFT_DATA_DIR
        cd maven
        mkdir repository
fi

cd $OPENSHIFT_REPO_DIR

export MAVEN_HOME = $OPENSHIFT_DATA_DIR/maven
export MAVEN_OPTS = "-Xms384m -Xmx412m"
export JAVA_HOME = $OPENSHIFT_DATA_DIR/java

export PATH = $JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

mvn -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml clean install
